### PR TITLE
Async flow breaker

### LINKED ISSUE #25: Improve `FlowBreaker` implementation
Currently `FlowBreaker` uses `Flow.takeWhile` which will terminate the stream when (if) another input element becomes available. An alternative implementation is possible, using `akka.stream.stage.AsyncStage` that would trigger stream termination immediately after `Cancellable.cancel()` were called.

Stages are documented in http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-customize.html 
Digging into `akka.stream.impl.fusing.MapAsync` implemention would probalby be a good start.

### PR DESCRIPTION
**Pull request by maciej**
Akka Steams 2.0-compatible.

Fixes #25

### CODE REVIEW

**Comment by maciej** [comment]
Hm… some strange things happen in the `watch()` method with the new FlowBreaker. I'm looking into that.

**Comment by rkrzewski** [comment]
We have a problem WRT source code formatting... I'm using Eclipse based Scala IDE, and you are using Idea. Is there any way we could keep the formatting consistent between these two, or one of us needs to switch IDEs? ;)

**Comment by maciej** [comment]
@rkrzewski looking at `UnzipWith2` code it seems that if it's downstream finishes (here FlowBreaker) the whole stage will be completed:

``` scala
      override def onDownstreamFinish(): Unit = {
        downstreamRunning -= 1
        if (downstreamRunning == 0) completeStage()
        else {
          if (pending0) pendingCount -= 1
          if (pendingCount == 0) pull(in)
        }
      }
    })
```

(from UnzipWithApply.scala:362)

At least that's how I understand it.

**Comment by maciej** [comment]
@rkrzewski everyone knows that IDEA is better ;-)

**Comment by rkrzewski** [comment]
Regarding unzip - you are right. Docs for `Unzip` say:

> **Cancels when** any downstream cancels

This means that even without the breaker, the unbounded source returned by `watch` would terminate correctly when it's connected sink cancels the incoming stream. That could be readily done by implementing an `ActorSubscriber` and using it's `cancel()` method, or using `Sink.foreach` handler that eventually throws an exception.

Let's keep it though, because this makes the API more elegant :) 

I'll merge the PR now, and you could look into making a PR in Akka Streams - I think that breaker would be a nice addition to `FlowOps`!

**Comment by maciej** [comment]
@rkrzewski correct, however than the API user would have to adapt the sink to be able to cancel the stream. With the `FlowBreaker` he can use the materialised value of the source.

**Comment by maciej** [comment]
Hi @ktoso, I'm mentioning you on this, as there is akka/akka#18612 open, which is a request for similar functionality in akka-streams. Would it be OK if I asked you if the code we wrote here would be a good start for a PR to this issue?

**Comment by ktoso** [comment]
I will need to read the code, on a hike right now though. It does not quite look like the same thing. The akka ticket requires internals and tracking completion more globally for the stream there I believe.

**Comment by rkrzewski** [comment]
@ktoso, you really shouldn't read GitHub notifications on a hike! ;)
I also think akka/akka#18612 has broader scope. `FlowBreakerStage` only helps with the cancellation side of the story, but not completion notification. However it's quite simple and immediately useful.

**Pull request merged**
